.SILENT:
project1:
	-g++ -fdiagnostics-format=json -g -std=c++14 ./compilecode/Project1/*.cpp -o auto_out1
project2:
	-g++ -fdiagnostics-format=json -g -std=c++14 ./compilecode/Project2/*.cpp -o auto_out2
project3:
	-g++ -fdiagnostics-format=json -g -std=c++14 ./compilecode/Project3/*.cpp -o auto_out3
project4:
	-g++ -fdiagnostics-format=json -g -std=c++14 ./compilecode/Project4/*.cpp -o auto_out4
